import { randomBytes } from 'node:crypto';
import type { Lang, LeaseDraft, PaymentIntent, PaymentKind, Property, TenantId } from '../contracts';
import { APP_NAME } from '../config/brand';
import { sha256Hex } from '../solana/hash';
import { findProperty, propertyTitle } from './catalog';
import { tenantDisplayName } from './tenants';

/** Lease parameters (not pricing logic): pricing.ts applies them. */
export const LEASE_MONTHS = 12;
export const DISCOUNT_USDC_BPS = 300;
export const DISCOUNT_ONTIME_BPS = 200;
const DAY_SECONDS = 24 * 60 * 60;
const USDC_DECIMALS = 1_000_000;

function toBaseUnits(usdc: number): string {
  return BigInt(Math.round(usdc * USDC_DECIMALS)).toString();
}

function isoDate(ms: number): string {
  return new Date(ms).toISOString().slice(0, 10);
}

/** Unix seconds of `baseTs` shifted by `months` calendar months (UTC). */
export function addMonthsTs(baseTs: number, months: number): number {
  const d = new Date(baseTs * 1000);
  d.setUTCMonth(d.getUTCMonth() + months);
  return Math.floor(d.getTime() / 1000);
}

export interface ContractParams {
  lang?: Lang;
  leaseId: string;
  tenantLabel: string;
  property: Property;
  startDate: string;
  months: number;
  rentUsdc: number;
  depositUsdc: number;
  dueDate: string;
}

/** English lease template (demo). */
function renderContractEn(p: ContractParams): string {
  return [
    'RESIDENTIAL LEASE AGREEMENT (DEMO)',
    '',
    `DEMO CONTRACT WITH SIMULATED DATA. This text was generated by ${APP_NAME} from a template for a hackathon demo.`,
    'It is not a legal document and it is not legal or tax advice. For a real lease, consult a licensed professional.',
    '',
    `Lease ID: ${p.leaseId}`,
    `Tenant: ${p.tenantLabel}`,
    'Landlord: Demo Landlord (simulated)',
    'Intermediary: Demo real-estate agency (simulated)',
    `Property: ${propertyTitle(p.property, 'en')} (catalog id ${p.property.id}), ${p.property.zone}, Salta, Argentina`,
    '',
    '1. Term.',
    `   ${p.months} months starting on ${p.startDate}.`,
    '2. Rent.',
    `   ${p.rentUsdc} USDC per month. The first rent payment is due on ${p.dueDate}; each following payment is due on`,
    '   the same day of each following month.',
    '3. Discounts.',
    `   Paying in USDC reduces the rent by ${DISCOUNT_USDC_BPS / 100}%. Paying on or before the due date reduces it by a`,
    `   further ${DISCOUNT_ONTIME_BPS / 100}%. Timeliness is determined by the confirmation time of the payment`,
    '   transaction on Solana devnet, never by a device clock.',
    '4. Security deposit.',
    `   ${p.depositUsdc} USDC (one month of rent), held in custody by the ${APP_NAME} platform during the lease (custodial escrow`,
    '   in this demo) and returned at move-out, less any amounts agreed by the parties.',
    '5. Payment record.',
    '   Each payment carries a memo with this lease ID and the SHA-256 hash of this exact contract text. No personal',
    '   data is written on-chain.',
    '6. Pets and use.',
    `   Residential use only. Pets: ${p.property.petsAllowed ? 'allowed' : 'not allowed'}, as stated in the listing.`,
    '',
    'Signed electronically by the parties (simulated).',
  ].join('\n');
}

/** Spanish lease template (demo). Same clauses as the English one; the hash is over this exact text. */
function renderContractEs(p: ContractParams): string {
  return [
    'CONTRATO DE LOCACIÓN DE VIVIENDA (DEMO)',
    '',
    `CONTRATO DE DEMOSTRACIÓN CON DATOS SIMULADOS. Este texto fue generado por ${APP_NAME} a partir de una plantilla para una demo de hackathon.`,
    'No es un documento legal ni constituye asesoramiento legal o impositivo. Para una locación real, consulte a un profesional matriculado.',
    '',
    `ID de contrato: ${p.leaseId}`,
    `Locatario: ${p.tenantLabel}`,
    'Locador: Locador de demostración (simulado)',
    'Intermediaria: Inmobiliaria de demostración (simulada)',
    `Inmueble: ${propertyTitle(p.property, 'es')} (id de catálogo ${p.property.id}), ${p.property.zone}, Salta, Argentina`,
    '',
    '1. Plazo.',
    `   ${p.months} meses a partir del ${p.startDate}.`,
    '2. Alquiler.',
    `   ${p.rentUsdc} USDC por mes. El primer pago vence el ${p.dueDate}; cada pago siguiente vence el mismo día`,
    '   de cada mes posterior.',
    '3. Descuentos.',
    `   Pagar en USDC reduce el alquiler un ${DISCOUNT_USDC_BPS / 100}%. Pagar en la fecha de vencimiento o antes lo reduce`,
    `   un ${DISCOUNT_ONTIME_BPS / 100}% adicional. La puntualidad se determina por la hora de confirmación de la transacción`,
    '   de pago en Solana devnet, nunca por el reloj de un dispositivo.',
    '4. Depósito en garantía.',
    `   ${p.depositUsdc} USDC (un mes de alquiler), mantenido en custodia por la plataforma ${APP_NAME} durante la locación (custodia`,
    '   centralizada en esta demo) y devuelto al finalizar, descontando los importes que acuerden las partes.',
    '5. Registro de pagos.',
    '   Cada pago lleva un memo con este ID de contrato y el hash SHA-256 del texto exacto de este contrato. No se escriben',
    '   datos personales en la blockchain.',
    '6. Mascotas y uso.',
    `   Uso exclusivamente residencial. Mascotas: ${p.property.petsAllowed ? 'permitidas' : 'no permitidas'}, según lo indicado en el aviso.`,
    '',
    'Firmado electrónicamente por las partes (simulado).',
  ].join('\n');
}

/** Renders the lease in `p.lang` (default English). The text, and therefore its SHA-256, differs per language. */
export function renderContract(p: ContractParams): string {
  return p.lang === 'es' ? renderContractEs(p) : renderContractEn(p);
}

/**
 * Builds the lease draft from the catalog and a fixed template in `lang` (default English). Deterministic except
 * leaseId and dates. The hash covers the exact text in that language, so ES and EN hashes differ by design.
 */
export function createLeaseDraft(tenantId: TenantId, propertyId: string, lang: Lang = 'en'): LeaseDraft {
  const property = findProperty(propertyId);
  if (!property) throw new Error(`Unknown property id: ${propertyId}`);

  const nowMs = Date.now();
  const leaseId = `ls_${randomBytes(8).toString('hex')}`;
  const startDate = isoDate(nowMs);
  const dueTs = Math.floor(nowMs / 1000) + DAY_SECONDS; // tomorrow, so the demo payment is on time
  const contractText = renderContract({
    lang,
    leaseId,
    tenantLabel: tenantDisplayName(tenantId, lang),
    property,
    startDate,
    months: LEASE_MONTHS,
    rentUsdc: property.priceUsdc,
    depositUsdc: property.priceUsdc,
    dueDate: isoDate(dueTs * 1000),
  });

  return {
    leaseId,
    tenantId,
    propertyId: property.id,
    startDate,
    months: LEASE_MONTHS,
    rentBaseUnits: toBaseUnits(property.priceUsdc),
    depositBaseUnits: toBaseUnits(property.priceUsdc),
    dueTs,
    discountUsdcBps: DISCOUNT_USDC_BPS,
    discountOntimeBps: DISCOUNT_ONTIME_BPS,
    lang,
    contractText,
    contractHash: sha256Hex(contractText),
  };
}

/** Typed payment request for lib/solana. Agents never touch Solana libraries. */
export function buildPaymentIntent(lease: LeaseDraft, kind: PaymentKind, monthIndex?: number): PaymentIntent {
  const base = {
    leaseId: lease.leaseId,
    kind,
    payer: lease.tenantId,
    contractHash: lease.contractHash,
    discountUsdcBps: lease.discountUsdcBps,
    discountOntimeBps: lease.discountOntimeBps,
  };
  if (kind === 'deposit') {
    return { ...base, listAmountBaseUnits: lease.depositBaseUnits, dueTs: lease.dueTs };
  }
  const month = monthIndex ?? 0;
  if (!Number.isInteger(month) || month < 0 || month >= lease.months) {
    throw new RangeError(`monthIndex must be an integer in [0, ${lease.months - 1}]`);
  }
  return { ...base, monthIndex: month, listAmountBaseUnits: lease.rentBaseUnits, dueTs: addMonthsTs(lease.dueTs, month) };
}
